### PR TITLE
Defined IFilter for use with functions in find namespace.

### PR DESCRIPTION
**Pull request by jojotastic777**
We can use this as an example for defining callbacks in the future as well.

### CODE REVIEW

**Review by Ehntae — COMMENTED** [review]
Are these changes tested and confirmed working as intended?

**Comment by jojotastic777** [comment]
I can double-check that the right now, at least as to whether or not code written with these definitions looks correct. As I do not have access to the transpiler, further testing would be up to you.

**Comment by Ehntae** [comment]
These type definitions are only relevant in the IDE and linting processes, so transpilation is not required. Double check to see if the callback syntax works as intended and it should be good.

**Comment by jojotastic777** [comment]
Callback syntax looks good with the following test code:
```typescript
let target = find.allPlayers((ent: Entity) => ent == chip().getOwner());
```

**Comment by Ehntae** [comment]
Fantastic

**Pull request merged**
